# Generated by Django 5.2.4 on 2025-07-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_delete_reveiw"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="review",
            name="genre",
        ),
        migrations.AddField(
            model_name="review",
            name="genre",
            field=models.ManyToManyField(to="reviews.genre"),
        ),
    ]
