# Generated by Django 5.2.4 on 2025-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_genre_remove_review_genre_review_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.FloatField(
                choices=[
                    (1.0, "1.0 점"),
                    (1.5, "1.5 점"),
                    (2.0, "2.0 점"),
                    (2.5, "2.5 점"),
                    (3.0, "3.0 점"),
                    (3.5, "3.5 점"),
                    (4.0, "4.0 점"),
                    (4.5, "4.5 점"),
                    (5.0, "5.0 점"),
                ]
            ),
        ),
    ]
